apiVersion: v1
kind: Service
metadata:
  name: fweb70577-service
  annotations:
    protectedClusterIPSVCName: multitool01-deployment
    metallb.universe.tf/loadBalancerIPs: 10.0.0.4
    service.beta.kubernetes.io/azure-dns-label-name: k8strainingmaster1
spec:
  sessionAffinity: ClientIP
  ports:
  - port: 8080
    name: rest
    targetPort: 80
  - port: 8888
    name: fweb70577-service-8888
    targetPort: 8888
  selector:
    app: fortiweb
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-config
data:
  SSH_HOST: ""
  SSH_PORT: "2222"
  SSH_USERNAME: "admin"
  SSH_NEW_PASSWORD: "Welcome.123"
  FORTIWEBIMAGENAME: "fweb70577"
  FORTIWEBSVCPORT:   "8888"
