apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: "cidata"
spec:
  source:
    http:
      url: "https://wandyeastasia.blob.core.windows.net/terraformps/cidata.iso"
  pvc:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: "1000Mi"
