apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: "fortiweblogdisk"
spec:
  source:
    http:
      url: "https://wandyeastasia.blob.core.windows.net/terraformps/log.qcow2"
  pvc:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: "50000Mi"
